name: Deploy DAGs to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 136.118.197.91
          username: airflow-dev
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 1. 실제 Airflow 실행 폴더로 이동
            cd ~/Apache_Airflow
            
            # 2. 만약 해당 폴더가 git 레포가 아니라면 초기 설정 (이미 되어있을 확률이 높지만 안전을 위해)
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/walter230/kdt-woongjin-2.git
            fi
            
            # 3. 최신 코드 가져오기 (main 브랜치 기준)
            git fetch --all
            git reset --hard origin/main
            
            # 4. 권한 설정 (Docker Airflow 컨테이너가 쓸 수 있도록 UID 50000 권한 부여)
            sudo chown -R 50000:0 ~/Apache_Airflow
            sudo chmod -R 775 ~/Apache_Airflow